// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrP4hqzdG2fp8ykFnNpytN-eKo_IIES4',
    appId: '1:559669431818:web:8b1de9b72ca37cb66099f3',
    messagingSenderId: '559669431818',
    projectId: 'todoapp-8262d',
    authDomain: 'todoapp-8262d.firebaseapp.com',
    storageBucket: 'todoapp-8262d.firebasestorage.app',
    measurementId: 'G-217W7HHLB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzBOAtt8qeXKC30xH9sMFsOlUb_CGC8Y',
    appId: '1:559669431818:android:6b1d838d803002236099f3',
    messagingSenderId: '559669431818',
    projectId: 'todoapp-8262d',
    storageBucket: 'todoapp-8262d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorg2FO1y51FE7JRu8GxdULTuZaHvdtwY',
    appId: '1:559669431818:ios:62ba80e85c886abb6099f3',
    messagingSenderId: '559669431818',
    projectId: 'todoapp-8262d',
    storageBucket: 'todoapp-8262d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorg2FO1y51FE7JRu8GxdULTuZaHvdtwY',
    appId: '1:559669431818:ios:62ba80e85c886abb6099f3',
    messagingSenderId: '559669431818',
    projectId: 'todoapp-8262d',
    storageBucket: 'todoapp-8262d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZrP4hqzdG2fp8ykFnNpytN-eKo_IIES4',
    appId: '1:559669431818:web:f0e02a5bf962af916099f3',
    messagingSenderId: '559669431818',
    projectId: 'todoapp-8262d',
    authDomain: 'todoapp-8262d.firebaseapp.com',
    storageBucket: 'todoapp-8262d.firebasestorage.app',
    measurementId: 'G-JCXSSG55QW',
  );
}
